removing gitcomfig from files and adding new bootstrap

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -6,20 +6,26 @@
 
 set -eu
 
-# Directory to look for bootstrap executables in
-BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+echo "0. Boostrapping"
 
-if [[ ! -d "$BOOTSTRAP_D" ]]; then
+echo "creating symlinks to config files"
+if eval "yadm alt"; then
+
+  # Directory to look for bootstrap executables in
+  BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
+  if [[ ! -d "$BOOTSTRAP_D" ]]; then
     echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
     exit 1
-fi
+  fi
 
-find "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
-	echo $bootstrap
-    if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
-        if ! "$bootstrap"; then
-            echo "Error: bootstrap '$bootstrap' failed" >&2
-            exit 1
-        fi
-    fi
-done
+  if eval "$BOOTSTRAP_D/bootstrap"; then
+    echo "Bootstrapping Complete"
+  else
+    echo "Bootstrapping Failed. exiting."
+    exit 1
+  fi
+
+else
+  echo "failed to create symlinks. exiting."
+  exit 1
+fi
